# Site
repository: gelsleichter/port_resume
favicon: images/Yuri_ico.png 
#favicon: images/favicon.ico 

# Personal info
name: Yuri Gelsleichter
title: Mapeamento digital de solos, GIS, monitoramento via sat√©lite e agricultura de precis√£o
email: yurigelsleichter@gmail.com
# website: https://gelsleichter.github.io/
website: https://datasitu.com

# Social links
# twitter_username: facespics
github_username:  yurigelsleichter
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: yurigelsleichter
linkedin_username: yurigelsleichter
# pinterest_username: jekyll
# youtube_username: yurigelsleichter
# googleplus_username: +jekyll

# About Section 
about_title: Sobre 
about_profile_image: images/yuri_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Sou Yuri Andrei Gelsleichter, T√©cnico em Mec√¢nica (IFSC, 2004), Engenheiro Ambiental (UNISUL, 2015), Doutor em Ci√™ncia, 
  Tecnologia e Inova√ß√£o em Agropecu√°ria (UFRRJ, 2020), P√≥s Doutorado (Universidade H√∫ngara de Ci√™ncias Agr√°rias, 2023). 

  Durante essa trajet√≥ria me tornei especialista em Mapeamento Digital de Solos e Meio Ambiente, Agricultura de Precis√£o,
  An√°lise e Visualiza√ß√£o de Dados aplicando a linguagem R de programa√ß√£o. 

  Atualmente trabalhando tamb√©m com sensoriamento remoto, minera√ß√£o e automa√ß√£o de dados e pesquisas na √°rea de classifica√ß√£o de solos e 
  espectro radiometria e agricultura de precis√£o. Co-fundador da (Data Situ](https://datasitu.com).

  [English CV üá∫üá∏](https://gelsleichter.github.io/en_resume/) 

  <!-- [CV em Portugu√™s üáßüá∑](https://gelsleichter.github.io/port_resume/) --> 
    
  <!-- aplicando a <mark> linguagem R </mark> de programa√ß√£o. [Veja este curr√≠culo em ingl√™s](https://gelsleichter.github.io/en_resume/) (This resume in English) -->
  
# Projects Section 
projects_title: Projetos Recentes

# Experience Section 
experience_title: Experi√™ncias internacionais 

# Education Section 
educaton_title: Educa√ß√£o

# More Section
more_title: Publica√ß√µes recentes 
more_content: | # this will include new lines to allow paragraphs
  Trabalhos mais relevantes: 
  
  Enhancing Soil Mapping with Hyperspectral Subsurface Images generated from soil lab Vis-SWIR spectra tested in southern Brazil; 2023; 
  Gelsleichter, Y.A.; Costa, E.M,; Anjos, L.H.C.; Marcondes, R.A.T; [doi](https://doi.org/10.1016/j.geodrs.2023.e00641)
  
  Past and Future Responses of Soil Water to Climate Change in Tropical and Subtropical Rainforest Systems in South America; 2023; 
  Ar√©valo, S.M.M.; Delgado, R.C.; Lindemann, D.S.; Gelsleichter, Y.A.; Pereira, M.G.; Rodrigues, R.A.; Justino, F.B.; Wanderley, H.S.; 
  Zonta, E.; Santana, R.O.; Souza; R.S.; [doi](https://doi.org/10.3390/atmos14040755)
  
  Degradation of South American biomes: What to expect for the future?; Delgado, R.C.; Santana, R.O.; Gelsleichter, Y.A.; 
  Pereira, M.G.; [doi](https://doi.org/10.1016/j.eiar.2022.106815)
  
  Mapping soil properties in a poorly-accessible area; Costa, E.M.; Pinheiro, H.S.K.; Anjos, L.H.C; Marcondes, R.A.T.; 
  Gelsleichter, Y.A.; [doi](https://doi.org/10.36783/18069657rbcs20190107)
  
  Spatial Bayesian belief networks: a participatory approach for mapping environmental vulnerability at the Itatiaia National Park, Brazil; 
  Costa, E.M.; Pinheiro, H.S.K.; Anjos, L.H.C; Gelsleichter, Y.A.; Marcondes, R.A.T.; [doi](https://doi.org/10.1007/s12665-020-09099-9)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
